### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "4230265613",
  "amount": 100000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "1000000003",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "ee8ee6c63c154110a1121d9931fae11a",
  "accountNumber": "9817643911",
  "amount": 100000
}

### query transcation
GET http://localhost:8080/transaction/7f15603b17944172acb2eb858de255b9