### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000003",
  "amount": 10000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000003",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "e9702e3713d9414f99601300424091c0",
  "accountNumber": "1000000003",
  "amount": 10000
}

### query transcation
GET http://localhost:8080/transaction/ac5f6d75c2c3400086a5d837ae0cf560